name = "northline-nxcore-commerce-bridge"
main = "src/index.js"
compatibility_date = "2026-09-02"

[[routes]]
pattern = "northline.aerovista.us/api/square/*"
zone_name = "aerovista.us"

[[routes]]
pattern = "northline.aerovista.us/v1/*"
zone_name = "aerovista.us"
